/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Tutorias;

import vista.Administracion.*;
import controlador.ControlarMatricula;
import controlador.dao.CicloDAO;
import controlador.dao.CuentaDao;
import controlador.dao.EstudianteDao;
import controlador.dao.ParaleloDAO;
import controlador.dao.RolDao;
import controlador.dao.TutoriaDao;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Matricula;
import modelo.tabla.ModeloTablaEstudiante;
import modelo.tabla.ModeloTablaMatricula;
import modelo.tabla.ModeloTablaTutorias;
import vista.utilidades.Utilidades;

/**
 *
 * @author cristian
 */
public class pnlTutorias extends javax.swing.JPanel {

    private CicloDAO cd = new CicloDAO();
    private ParaleloDAO pd = new ParaleloDAO();
    private CuentaDao cuentad = new CuentaDao();
    private RolDao rld = new RolDao();
    private EstudianteDao ed = new EstudianteDao();
    private TutoriaDao td = new TutoriaDao();
    private ModeloTablaTutorias modelo = new ModeloTablaTutorias();
    private int pos = -1;

    /**
     * Creates new form pnlHome
     */
    public pnlTutorias() {
        initComponents();
        cargarTutorias();

    }

    public void cargarTutorias() {
        modelo.setDatos(td.listar());
        tblTutorias.setModel(modelo);
        tblTutorias.updateUI();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTutorias = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnCrearTutoria = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblTutorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTutorias);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 255));
        jLabel2.setText("TUTORIAS");

        btnCrearTutoria.setText("Crear Tutoria");
        btnCrearTutoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTutoriaActionPerformed(evt);
            }
        });

        jButton1.setText("Desactivar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearTutoria)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnCrearTutoria)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearTutoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTutoriaActionPerformed
        pnlTuto crearTutorias = new pnlTuto();
        JFrame frame = new JFrame("Crear Tutoría");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Cierra solo la ventana actual al hacer clic en cerrar
        frame.getContentPane().add(crearTutorias);
        frame.pack();
        frame.setLocationRelativeTo(null); // Centra el frame en la pantalla
        frame.setVisible(true);

    }//GEN-LAST:event_btnCrearTutoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearTutoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTutorias;
    // End of variables declaration//GEN-END:variables
}
